forum_homepage:
    path:     /
    defaults: { _controller: ForumBundle:Default:forum }
forum:
    path:     /forum
    defaults: { _controller: ForumBundle:forum:forum }
forum-topics:
    path:     /forum/{id}/topics
    defaults: { _controller: ForumBundle:forum:displaytopics}
my-topics:
    path:     /forum/topics
    defaults: { _controller: ForumBundle:Topic:displayUserTopics}